const TEAM_NAME_PT: Record<string, string> = {
  // CONMEBOL
  'Brazil': 'Brasil',
  'Argentina': 'Argentina',
  'Colombia': 'Colômbia',
  'Ecuador': 'Equador',
  'Uruguay': 'Uruguai',
  'Paraguay': 'Paraguai',
  'Venezuela': 'Venezuela',
  'Chile': 'Chile',
  'Bolivia': 'Bolívia',
  'Peru': 'Peru',

  // CONCACAF
  'United States': 'Estados Unidos',
  'Mexico': 'México',
  'Canada': 'Canadá',
  'Honduras': 'Honduras',
  'Costa Rica': 'Costa Rica',
  'Panama': 'Panamá',
  'Jamaica': 'Jamaica',
  'El Salvador': 'El Salvador',
  'Guatemala': 'Guatemala',
  'Haiti': 'Haiti',
  'Trinidad and Tobago': 'Trinidad e Tobago',
  'Curaçao': 'Curaçao',
  'Cuba': 'Cuba',
  'Martinique': 'Martinica',
  'Guadeloupe': 'Guadalupe',
  'Suriname': 'Suriname',
  'Nicaragua': 'Nicarágua',
  'Belize': 'Belize',
  'Bermuda': 'Bermudas',
  'Barbados': 'Barbados',
  'Guyana': 'Guiana',
  'Dominican Republic': 'República Dominicana',
  'Puerto Rico': 'Porto Rico',

  // UEFA
  'Germany': 'Alemanha',
  'Spain': 'Espanha',
  'France': 'França',
  'England': 'Inglaterra',
  'Portugal': 'Portugal',
  'Netherlands': 'Holanda',
  'Belgium': 'Bélgica',
  'Italy': 'Itália',
  'Croatia': 'Croácia',
  'Serbia': 'Sérvia',
  'Switzerland': 'Suíça',
  'Denmark': 'Dinamarca',
  'Austria': 'Áustria',
  'Turkey': 'Turquia',
  'Türkiye': 'Turquia',
  'Hungary': 'Hungria',
  'Slovakia': 'Eslováquia',
  'Scotland': 'Escócia',
  'Czech Republic': 'República Tcheca',
  'Czechia': 'República Tcheca',
  'Wales': 'País de Gales',
  'Poland': 'Polônia',
  'Ukraine': 'Ucrânia',
  'Sweden': 'Suécia',
  'Norway': 'Noruega',
  'Greece': 'Grécia',
  'Romania': 'Romênia',
  'Albania': 'Albânia',
  'Slovenia': 'Eslovênia',
  'Bosnia and Herzegovina': 'Bósnia e Herzegovina',
  'North Macedonia': 'Macedônia do Norte',
  'Iceland': 'Islândia',
  'Finland': 'Finlândia',
  'Republic of Ireland': 'Irlanda',
  'Ireland': 'Irlanda',
  'Northern Ireland': 'Irlanda do Norte',
  'Kosovo': 'Kosovo',
  'Montenegro': 'Montenegro',
  'Georgia': 'Geórgia',
  'Bulgaria': 'Bulgária',
  'Israel': 'Israel',
  'Russia': 'Rússia',
  'Luxembourg': 'Luxemburgo',
  'Kazakhstan': 'Cazaquistão',
  'Andorra': 'Andorra',
  'Moldova': 'Moldávia',
  'Estonia': 'Estônia',
  'Latvia': 'Letônia',
  'Lithuania': 'Lituânia',
  'Belarus': 'Bielorrússia',
  'Cyprus': 'Chipre',
  'Armenia': 'Armênia',
  'Azerbaijan': 'Azerbaijão',
  'Malta': 'Malta',
  'Faroe Islands': 'Ilhas Faroe',
  'San Marino': 'San Marino',
  'Gibraltar': 'Gibraltar',
  'Liechtenstein': 'Liechtenstein',

  // AFC
  'Japan': 'Japão',
  'South Korea': 'Coreia do Sul',
  'Korea Republic': 'Coreia do Sul',
  'Iran': 'Irã',
  'IR Iran': 'Irã',
  'Saudi Arabia': 'Arábia Saudita',
  'Australia': 'Austrália',
  'Qatar': 'Catar',
  'China PR': 'China',
  'China': 'China',
  'Uzbekistan': 'Uzbequistão',
  'Jordan': 'Jordânia',
  'Iraq': 'Iraque',
  'Oman': 'Omã',
  'Bahrain': 'Bahrein',
  'United Arab Emirates': 'Emirados Árabes Unidos',
  'Kuwait': 'Kuwait',
  'Palestine': 'Palestina',
  'Syria': 'Síria',
  'Kyrgyzstan': 'Quirguistão',
  'Tajikistan': 'Tajiquistão',
  'India': 'Índia',
  'Indonesia': 'Indonésia',
  'Vietnam': 'Vietnã',
  'Thailand': 'Tailândia',
  'Malaysia': 'Malásia',
  'Philippines': 'Filipinas',

  // CAF
  'Morocco': 'Marrocos',
  'Senegal': 'Senegal',
  'Nigeria': 'Nigéria',
  'Ivory Coast': 'Costa do Marfim',
  "Côte d'Ivoire": 'Costa do Marfim',
  'Egypt': 'Egito',
  'Cameroon': 'Camarões',
  'Ghana': 'Gana',
  'Algeria': 'Argélia',
  'Tunisia': 'Tunísia',
  'Mali': 'Mali',
  'Congo DR': 'R.D. do Congo',
  'DR Congo': 'R.D. do Congo',
  "Democratic Republic of the Congo": 'R.D. do Congo',
  'South Africa': 'África do Sul',
  'Cape Verde': 'Cabo Verde',
  'Gabon': 'Gabão',
  'Zambia': 'Zâmbia',
  'Zimbabwe': 'Zimbábue',
  'Guinea': 'Guiné',
  'Tanzania': 'Tanzânia',
  'Uganda': 'Uganda',
  'Ethiopia': 'Etiópia',
  'Angola': 'Angola',
  'Mozambique': 'Moçambique',
  'Kenya': 'Quênia',
  'Burkina Faso': 'Burkina Faso',
  'Benin': 'Benin',
  'Gambia': 'Gâmbia',
  'Sudan': 'Sudão',
  'Libya': 'Líbia',
  'Mauritania': 'Mauritânia',
  'Equatorial Guinea': 'Guiné Equatorial',
  'Guinea-Bissau': 'Guiné-Bissau',
  'Namibia': 'Namíbia',
  'Niger': 'Níger',
  'Rwanda': 'Ruanda',
  'Sierra Leone': 'Serra Leoa',
  'Somalia': 'Somália',
  'Togo': 'Togo',

  // OFC
  'New Zealand': 'Nova Zelândia',
  'Fiji': 'Fiji',
  'Papua New Guinea': 'Papua Nova Guiné',
  'Solomon Islands': 'Ilhas Salomão',
  'Vanuatu': 'Vanuatu',
  'Tahiti': 'Taiti',
}

export function translateTeamName(name: string): string {
  return TEAM_NAME_PT[name] ?? name
}
